version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
        # this ignores version updates which are handled via renovate
    # but lets us still do security updates
    ignore:
      - dependency-name: "*"
