version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/gax"
      - "/tools"
    schedule:
      interval: "daily"
    # this ignores version updates which are handled via renovate
    # but lets us still do security updates
    ignore:
      - dependency-name: "*"
